

/* **** Create PS_CATALOGO_CAMPO - Lista de CAMPO_CATALOGO  **** */
CREATE PROCEDURE [dbo].[PS_CATALOGO_CAMPO]
AS BEGIN
SELECT ID_CATALOGO_CAMPO,NOMBRE,ESTADO,puede_persistir FROM CATALOGO_CAMPO
END 





/* **** Create PS_DETALLE_CATALOGO_CAMP - Obtiene el detalle de un CATALOGO_CAMPO por ID_CATALOGO_CAMPO **** */

CREATE procedure [dbo].[PS_DETALLE_CATALOGO_CAMPO]
(@ID_CATALOGO_CAMPO INT)
AS  BEGIN
SELECT * FROM CATALOGO_CAMPO WHERE id_catalogo_campo=@ID_CATALOGO_CAMPO
END 



  /* **** Create PU_CATALOGO_CAMPO - Actualiza un LOGCAMPO **** */
  CREATE PROCEDURE [dbo].[PU_CATALOGO_CAMPO]
(@ID_CATALOGO_CAMPO INT,
@ESTADO SMALLINT,
@PUEDE_PERSISTIR SMALLINT)
AS BEGIN
UPDATE CATALOGO_CAMPO 
SET estado=@ESTADO,puede_persistir=@PUEDE_PERSISTIR
WHERE id_catalogo_campo=@ID_CATALOGO_CAMPO
END


