//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ServiceSunatPadron {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CltSunat", Namespace="http://schemas.datacontract.org/2004/07/TT.EOL.Coplementos")]
    [System.SerializableAttribute()]
    public partial class CltSunat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonsocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string condicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoviaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreviaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigozonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipozonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string interiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manzanaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kilometroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool agenteretencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool buencontribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string obligatoriedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool flagerrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                if ((object.ReferenceEquals(this.rucField, value) != true)) {
                    this.rucField = value;
                    this.RaisePropertyChanged("ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string razonsocial {
            get {
                return this.razonsocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonsocialField, value) != true)) {
                    this.razonsocialField = value;
                    this.RaisePropertyChanged("razonsocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string condicion {
            get {
                return this.condicionField;
            }
            set {
                if ((object.ReferenceEquals(this.condicionField, value) != true)) {
                    this.condicionField = value;
                    this.RaisePropertyChanged("condicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.ubigeoField, value) != true)) {
                    this.ubigeoField = value;
                    this.RaisePropertyChanged("ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string tipovia {
            get {
                return this.tipoviaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoviaField, value) != true)) {
                    this.tipoviaField = value;
                    this.RaisePropertyChanged("tipovia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string nombrevia {
            get {
                return this.nombreviaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreviaField, value) != true)) {
                    this.nombreviaField = value;
                    this.RaisePropertyChanged("nombrevia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string codigozona {
            get {
                return this.codigozonaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigozonaField, value) != true)) {
                    this.codigozonaField = value;
                    this.RaisePropertyChanged("codigozona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string tipozona {
            get {
                return this.tipozonaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipozonaField, value) != true)) {
                    this.tipozonaField = value;
                    this.RaisePropertyChanged("tipozona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string interior {
            get {
                return this.interiorField;
            }
            set {
                if ((object.ReferenceEquals(this.interiorField, value) != true)) {
                    this.interiorField = value;
                    this.RaisePropertyChanged("interior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                if ((object.ReferenceEquals(this.loteField, value) != true)) {
                    this.loteField = value;
                    this.RaisePropertyChanged("lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string manzana {
            get {
                return this.manzanaField;
            }
            set {
                if ((object.ReferenceEquals(this.manzanaField, value) != true)) {
                    this.manzanaField = value;
                    this.RaisePropertyChanged("manzana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string kilometro {
            get {
                return this.kilometroField;
            }
            set {
                if ((object.ReferenceEquals(this.kilometroField, value) != true)) {
                    this.kilometroField = value;
                    this.RaisePropertyChanged("kilometro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool agenteretencion {
            get {
                return this.agenteretencionField;
            }
            set {
                if ((this.agenteretencionField.Equals(value) != true)) {
                    this.agenteretencionField = value;
                    this.RaisePropertyChanged("agenteretencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool buencontribuyente {
            get {
                return this.buencontribuyenteField;
            }
            set {
                if ((this.buencontribuyenteField.Equals(value) != true)) {
                    this.buencontribuyenteField = value;
                    this.RaisePropertyChanged("buencontribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string obligatoriedad {
            get {
                return this.obligatoriedadField;
            }
            set {
                if ((object.ReferenceEquals(this.obligatoriedadField, value) != true)) {
                    this.obligatoriedadField = value;
                    this.RaisePropertyChanged("obligatoriedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string fechaingreso {
            get {
                return this.fechaingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaingresoField, value) != true)) {
                    this.fechaingresoField = value;
                    this.RaisePropertyChanged("fechaingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool flagerror {
            get {
                return this.flagerrorField;
            }
            set {
                if ((this.flagerrorField.Equals(value) != true)) {
                    this.flagerrorField = value;
                    this.RaisePropertyChanged("flagerror");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSunatPadron.IwsPadron")]
    public interface IwsPadron {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPadron/BuscarClienteSunat", ReplyAction="http://tempuri.org/IwsPadron/BuscarClienteSunatResponse")]
        Model.ServiceSunatPadron.CltSunat BuscarClienteSunat(string ouser, string oclave, string nroruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPadron/BuscarClienteSunat", ReplyAction="http://tempuri.org/IwsPadron/BuscarClienteSunatResponse")]
        System.Threading.Tasks.Task<Model.ServiceSunatPadron.CltSunat> BuscarClienteSunatAsync(string ouser, string oclave, string nroruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsPadronChannel : Model.ServiceSunatPadron.IwsPadron, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsPadronClient : System.ServiceModel.ClientBase<Model.ServiceSunatPadron.IwsPadron>, Model.ServiceSunatPadron.IwsPadron {
        
        public IwsPadronClient() {
        }
        
        public IwsPadronClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsPadronClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPadronClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPadronClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.ServiceSunatPadron.CltSunat BuscarClienteSunat(string ouser, string oclave, string nroruc) {
            return base.Channel.BuscarClienteSunat(ouser, oclave, nroruc);
        }
        
        public System.Threading.Tasks.Task<Model.ServiceSunatPadron.CltSunat> BuscarClienteSunatAsync(string ouser, string oclave, string nroruc) {
            return base.Channel.BuscarClienteSunatAsync(ouser, oclave, nroruc);
        }
    }
}
